apiVersion: v1
kind: Pod
metadata:
  name: nv-embedqa-e5-v5
spec:
  containers:
  - name: nv-embedqa-e5-v5
    image: "nvcr.io/nim/nvidia/nv-embedqa-e5-v5:1.0.0"
    env:
    - name: NGC_API_KEY
      valueFrom:
        secretKeyRef:
          name: ngc-api
          key: NGC_CLI_API_KEY
  imagePullSecrets:
  - name: nvcrimagepullsecret
