apiVersion: v1
kind: Pod
metadata:
  name: llama3-8b
spec:
  containers:
  - name: llama3-8b
    image: "nvcr.io/nim/meta/llama3-8b-instruct:1.0.3"
    env:
    - name: NGC_API_KEY
      valueFrom:
        secretKeyRef:
          name: ngc-api
          key: NGC_CLI_API_KEY
  imagePullSecrets:
  - name: nvcrimagepullsecret
